name: Build Windows Executable

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Install UPX (for compression)
      run: choco install upx

    - name: Build Lightweight Executable (Onefile)
      shell: bash
      run: |
        pyinstaller --noconfirm --onefile --windowed --clean \
        --name "Glans_Miya" \
        --add-data "README.md;." \
        --exclude-module "tkinter" \
        --exclude-module "unittest" \
        --exclude-module "email" \
        --exclude-module "pydoc" \
        --exclude-module "http" \
        --upx-dir "C:/ProgramData/chocolatey/bin" \
        "Glans_Miya.py"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Glans_Miya-v1.0.1
        path: dist/Glans_Miya.exe